import main_image from "./main_image.png"
import circle from "./111-1110988_image-result-for-hand-drawing-a-circle-hand.png"
import curvedArrow from "./quirky-curved-blue-arrow.png"
import graphEmoji from "./icons8-chart-increasing-96.png"
import paintingBrush from "./quirky-painting-with-a-brush-1.png"
import blueSquiggle from "./quirky-blue-squiggle.png"
import underlines from "./quirky-two-blue-curved-lines.png"
import abstractIllustration from "./pexels-dids-3705653.jpg"
import aboutPageImage1 from "./9-91459_person-autor-2-0-jak-wyda-wasn-ksik-i.png"
import curvedLine from "./jelly-yellow-curved-line.png"
import quotationMark from "./3d-fluency-quote-left.png"
import user from "./3d-fluency-person.png"
import pencilAndRuler from "./3d-fluency-pencil-and-ruler.png"
import layers from "./3d-fluency-layers.png"
import inkyText from "./inky-text-2.png"
import alan_turing_img from "./1-Figure2-1-removebg-preview.png"

export { alan_turing_img ,main_image, circle, curvedArrow, graphEmoji, paintingBrush, blueSquiggle, underlines, abstractIllustration, aboutPageImage1, curvedLine, quotationMark, user, pencilAndRuler, layers, inkyText }